import type { CompletenessStep } from './types';

/**
 * The step registry — every action a user can take to complete their pension picture.
 *
 * Weights are calibrated so that:
 * - Profile + career basics = ~25%
 * - Pension documents = ~35%
 * - Insurance + Pillar 3 = ~15%
 * - Family access = ~15%
 * - Planning & review = ~10%
 */
export const STEPS: CompletenessStep[] = [
  // ── Profile ──────────────────────────────────────────
  {
    id: 'profile-created',
    label: 'Create your profile',
    why: 'Your birth year, gender, and residence country determine which pension rules apply — and when you can retire.',
    how: 'Complete the onboarding wizard with your personal details.',
    effort: '2 minutes',
    weight: 5,
    category: 'profile',
    countries: null,
    href: '/',
    cta: 'Open Onboarding',
    tier: 'free',
    icon: '👤',
    priority: 0,
  },
  {
    id: 'retirement-goal-set',
    label: 'Set your retirement income goal',
    why: 'Without a target, there\'s no way to measure your gap. This number drives every recommendation.',
    how: 'Enter your desired monthly retirement income in the onboarding wizard or estimation page.',
    effort: '1 minute',
    weight: 5,
    category: 'profile',
    countries: null,
    href: '/estimation',
    cta: 'Set Goal',
    tier: 'free',
    icon: '🎯',
    priority: 1,
  },

  // ── Career ───────────────────────────────────────────
  {
    id: 'employment-history',
    label: 'Add your employment history',
    why: 'Each employment period maps to pension rights in that country. Missing periods mean missing pension income.',
    how: 'Upload your CV or add periods manually. RetirAI extracts countries, dates, and employers automatically.',
    effort: '5 minutes',
    weight: 10,
    category: 'career',
    countries: null,
    href: '/career',
    cta: 'Add Employment',
    tier: 'free',
    icon: '💼',
    priority: 2,
  },
  {
    id: 'salary-data',
    label: 'Verify salary data for all periods',
    why: 'Pension formulas use your salary history directly. The French SAM uses your best 25 years; Luxembourg uses career-average earnings.',
    how: 'Click each employment period and enter your gross annual salary. Check old payslips or tax returns if unsure.',
    effort: '10 minutes',
    weight: 5,
    category: 'career',
    countries: null,
    href: '/career',
    cta: 'Verify Salaries',
    tier: 'free',
    icon: '💰',
    priority: 3,
  },

  // ── Pension Documents ────────────────────────────────
  {
    id: 'doc-fr-career',
    label: 'Upload French career extract (Releve de Carriere)',
    why: 'This document contains your validated trimestres and salary history — the two inputs to the French pension formula. Without it, your estimate has +/-15% uncertainty.',
    how: 'Request it from lassuranceretraite.fr (free, instant PDF) or call CNAV at 3960. It\'s called "Releve de carriere".',
    effort: '5 minutes online',
    weight: 10,
    category: 'documents',
    countries: ['FR'],
    href: '/vault',
    cta: 'Upload Document',
    tier: 'free',
    icon: '📋',
    priority: 10,
  },
  {
    id: 'doc-ch-ahv',
    label: 'Upload Swiss AHV/AVS extract',
    why: 'Shows your contribution years and registered income — determines your AVS scale number and monthly pension.',
    how: 'Request from your cantonal SVA (Sozialversicherungsanstalt) or via ahv-iv.ch. Takes 1-2 weeks by post, or request online.',
    effort: '5 minutes to request, 1-2 weeks to receive',
    weight: 8,
    category: 'documents',
    countries: ['CH'],
    href: '/vault',
    cta: 'Upload Document',
    tier: 'free',
    icon: '🏛️',
    priority: 11,
  },
  {
    id: 'doc-ch-p2',
    label: 'Upload Swiss workplace pension statement (Vorsorgeausweis)',
    why: 'Your workplace pension is likely your largest single pension asset. For Mats, it adds EUR 1,040/mo plus a EUR 210,000 capital option.',
    how: 'Log into your pension fund portal (e.g. UBS, Swisscanto, AXA) or call them. Ask for your annual "Vorsorgeausweis".',
    effort: '5 minutes',
    weight: 12,
    category: 'documents',
    countries: ['CH'],
    href: '/vault',
    cta: 'Upload Document',
    tier: 'pro',
    icon: '📊',
    priority: 12,
  },
  {
    id: 'doc-lu-career',
    label: 'Upload Luxembourg career extract (Extrait de Carriere)',
    why: 'Confirms your insurance months and salary points with CNAP — directly affects your proportional pension component.',
    how: 'Request via myguichet.lu or visit CNAP at 1a bd Prince Henri, Luxembourg. Online requests arrive in 5-10 business days.',
    effort: '5 minutes to request',
    weight: 10,
    category: 'documents',
    countries: ['LU'],
    href: '/vault',
    cta: 'Upload Document',
    tier: 'free',
    icon: '📋',
    priority: 13,
  },

  // ── Insurance Documents ──────────────────────────────
  {
    id: 'insurance-life',
    label: 'Add life insurance policies',
    why: 'Life insurance (assurance vie) is often the largest unclaimed asset — EUR 5.4B unclaimed in France alone. Your family needs to know these exist.',
    how: 'Check your records for any assurance vie, Lebensversicherung, or life insurance contracts. Upload the latest annual statement.',
    effort: '10 minutes',
    weight: 7,
    category: 'insurance',
    countries: null,
    href: '/vault',
    cta: 'Add Policy',
    tier: 'pro',
    icon: '🛡️',
    priority: 20,
  },
  {
    id: 'insurance-p3',
    label: 'Add personal savings accounts',
    why: 'Swiss personal savings (3a/3b) and Luxembourg prevoyance-vieillesse (Art. 111bis) are tax-advantaged and often forgotten. They could add EUR 200-500/mo.',
    how: 'Check with your bank or insurer for any 3a/3b policies. In Luxembourg, check for prevoyance-vieillesse contracts.',
    effort: '10 minutes',
    weight: 8,
    category: 'insurance',
    countries: ['CH', 'LU'],
    href: '/vault',
    cta: 'Add Account',
    tier: 'pro',
    icon: '🏦',
    priority: 21,
  },

  // ── Family Access ────────────────────────────────────
  {
    id: 'family-member-added',
    label: 'Add a family member',
    why: 'If something happens to you, your family needs to know where your pensions and insurance are.',
    how: 'Go to Family Access and add your spouse or next of kin with their email address.',
    effort: '2 minutes',
    weight: 5,
    category: 'family',
    countries: null,
    href: '/family',
    cta: 'Add Family Member',
    tier: 'pro',
    icon: '👨‍👩‍👧',
    priority: 30,
  },
  {
    id: 'family-emergency-packet',
    label: 'Generate emergency packet',
    why: 'A personalized PDF with every account number, institution contact, and claim step — everything your family needs in one place.',
    how: 'Once your documents are uploaded, click "Generate Emergency Packet" on the Family Access page.',
    effort: '1 minute',
    weight: 5,
    category: 'family',
    countries: null,
    href: '/family',
    cta: 'Generate Packet',
    tier: 'family',
    icon: '📦',
    priority: 31,
  },
  {
    id: 'family-beneficiary-review',
    label: 'Review beneficiary designations',
    why: 'Outdated beneficiaries (ex-spouse, deceased parent) can delay or misdirect claims. A quick review prevents costly legal disputes.',
    how: 'Check each insurance policy and workplace pension statement for the named beneficiary. Update directly with the provider if needed.',
    effort: '15 minutes',
    weight: 5,
    category: 'family',
    countries: null,
    href: '/family',
    cta: 'Review Beneficiaries',
    tier: 'family',
    icon: '✏️',
    priority: 32,
  },

  // ── Planning & Review ────────────────────────────────
  {
    id: 'review-gaps',
    label: 'Review detected career gaps',
    why: 'Career gaps mean missing contribution years. Some are correctable — you can buy back missing trimestres in France or voluntary contributions in Luxembourg.',
    how: 'Go to the Career page and review each flagged gap. Mark them as intentional or explore correction options.',
    effort: '5 minutes',
    weight: 5,
    category: 'planning',
    countries: null,
    href: '/career',
    cta: 'Review Gaps',
    tier: 'free',
    icon: '🔍',
    priority: 40,
  },
  {
    id: 'review-radar',
    label: 'Review legislative alerts',
    why: 'Pension laws change. A single reform can shift your retirement date by a year or reduce your income by hundreds per month.',
    how: 'Check the Legislative Radar for any high-priority alerts affecting your countries.',
    effort: '3 minutes',
    weight: 5,
    category: 'planning',
    countries: null,
    href: '/radar',
    cta: 'View Radar',
    tier: 'pro',
    icon: '📡',
    priority: 41,
  },
  {
    id: 'run-simulation',
    label: 'Run a retirement simulation',
    why: 'See how different retirement ages, contribution strategies, and tax residencies affect your income. Find the optimal scenario.',
    how: 'Go to the Tax Simulation page and adjust the sliders to explore scenarios.',
    effort: '5 minutes',
    weight: 5,
    category: 'planning',
    countries: null,
    href: '/simulation',
    cta: 'Run Simulation',
    tier: 'pro',
    icon: '📈',
    priority: 42,
  },
];
