import type {
  UserProfile, EmploymentPeriod, PensionGap, PensionBreakdown,
  ProductOffer, PensionDocument, RiskAlert, FamilyMember, CapitalComponent,
  ServicePackage, ServiceRequest,
} from './types';

export const userProfile: UserProfile = {
  firstName: 'Mats',
  lastName: 'Karlsson',
  initials: 'MK',
  dateOfBirth: '1981-03-15',
  residenceCountry: 'LU',
  residenceLabel: '🇱🇺 Luxembourg · multi-country career · 3 countries',
  targetRetirementAge: 64,
  monthlyIncomeGoal: 5500,
};

export const employmentPeriods: EmploymentPeriod[] = [
  {
    id: 'ep-1',
    country: 'LU',
    employer: '',
    role: '',
    startDate: 'Apr 2020',
    endDate: null,
    grossSalary: 92000,
    currency: 'EUR',
    pillars: [],
    verified: false,
    insuranceYears: 6.0,
    notes: 'Pillar 1 contributions estimated from salary and dates. Upload Extrait de Carrière to verify.',
  },
  {
    id: 'ep-2',
    country: 'CH',
    employer: '',
    role: '',
    startDate: 'Sep 2014',
    endDate: 'Dec 2019',
    grossSalary: 135000,
    currency: 'CHF',
    pillars: [],
    verified: false,
    insuranceYears: 5.3,
    notes: 'Pillar 1 contributions estimated from salary and dates. Upload AHV/AVS extract to verify.',
  },
  {
    id: 'ep-3',
    country: 'FR',
    employer: '',
    role: '',
    startDate: 'Jun 2008',
    endDate: 'Jul 2013',
    grossSalary: 55000,
    currency: 'EUR',
    pillars: [],
    verified: false,
    insuranceYears: 5.1,
    notes: 'Pillar 1 contributions estimated from salary and dates. Upload Relevé de Carrière to verify.',
  },
  {
    id: 'ep-4',
    country: 'FR',
    employer: '',
    role: '',
    startDate: 'Sep 2003',
    endDate: 'May 2008',
    grossSalary: 38000,
    currency: 'EUR',
    pillars: [],
    verified: false,
    insuranceYears: 4.7,
    notes: 'Pillar 1 contributions estimated from salary and dates. Upload Relevé de Carrière to verify.',
  },
];

export const pensionGaps: PensionGap[] = [
  {
    id: 'gap-1',
    period: 'Jan–Mar 2020',
    country: 'LU',
    months: 3,
    monthlyImpact: 120,
    correctable: true,
    correctionCost: 1200,
    description: 'Transition gap detected between your Switzerland and Luxembourg periods. Below CNAP 3-month validation threshold.',
  },
  {
    id: 'gap-2',
    period: 'Aug 2013 – Aug 2014',
    country: 'FR',
    months: 14,
    monthlyImpact: 45,
    correctable: false,
    description: 'No employment data between your two French periods. Were you working, studying, or abroad? Add the missing period to improve your estimate.',
  },
];

export const pensionBreakdown: PensionBreakdown[] = [
  {
    country: 'FR',
    countryLabel: 'France',
    flag: '🇫🇷',
    pillar1: 1220,
    pillar1Body: 'CNAV · 10.9 yrs',
    pillar1Years: 10.9,
    pillar2: 0,
    pillar2Body: 'Not yet tracked — upload documents',
    pillar2Status: 'unlocated',
    pillar3: 0,
    pillar3Body: '—',
    total: 1220,
  },
  {
    country: 'CH',
    countryLabel: 'Switzerland',
    flag: '🇨🇭',
    pillar1: 320,
    pillar1Body: 'AVS · 5.3 yrs',
    pillar1Years: 5.3,
    pillar2: 0,
    pillar2Body: 'Not yet tracked — upload Vorsorgeausweis',
    pillar2Status: 'unlocated',
    pillar3: 0,
    pillar3Body: '—',
    total: 320,
  },
  {
    country: 'LU',
    countryLabel: 'Luxembourg',
    flag: '🇱🇺',
    pillar1: 980,
    pillar1Body: 'CNAP · 6.0 yrs · est.',
    pillar1Years: 6.0,
    pillar2: 0,
    pillar2Body: 'Not yet tracked — upload pension fund statement',
    pillar2Status: 'unlocated',
    pillar3: 0,
    pillar3Body: '—',
    total: 980,
  },
];

export const productOffers: ProductOffer[] = [
  {
    id: 'offer-1',
    provider: 'Foyer',
    providerInitial: 'F',
    providerGradient: 'linear-gradient(135deg, #1a365d, #2a4a7f)',
    country: 'Luxembourg',
    productName: 'Prévoyance-vieillesse',
    description: 'Tax-advantaged private pension under Art. 111bis LIR. Up to €3,200/yr tax-deductible. Capital or annuity at retirement.',
    gapImpact: 450,
    monthlyContribution: 267,
    horizon: 20,
    isBestMatch: false,
  },
  {
    id: 'offer-2',
    provider: 'Sogelife',
    providerInitial: 'S',
    providerGradient: 'linear-gradient(135deg, #7b2d8e, #a855f7)',
    country: 'Luxembourg',
    productName: 'Assurance-vie multisupport',
    description: 'Unit-linked life insurance with flexible allocation. Combines capital growth with inheritance planning. No contribution cap.',
    gapImpact: 550,
    monthlyContribution: 400,
    horizon: 20,
    isBestMatch: true,
  },
  {
    id: 'offer-3',
    provider: 'Swissquote',
    providerInitial: 'S',
    providerGradient: 'linear-gradient(135deg, #0d7c3e, #10b981)',
    country: 'Luxembourg',
    productName: 'ETF Savings Plan',
    description: 'Automated monthly investing in diversified global ETFs. Low fees (TER 0.12–0.25%). Full flexibility — pause, adjust, or withdraw anytime.',
    gapImpact: 350,
    monthlyContribution: 250,
    horizon: 20,
    isBestMatch: false,
  },
];

export const documentsBefore: PensionDocument[] = [
  { id: 'doc-1', name: 'Relevé de Carrière', country: 'FR', flag: '🇫🇷', source: 'CNAV', status: 'missing', date: 'Not uploaded', type: 'Career Extract', icon: '📋' },
  { id: 'doc-2', name: 'Vorsorgeausweis', country: 'CH', flag: '🇨🇭', source: 'Pension Fund', status: 'missing', date: 'Not uploaded', type: 'Pension Statement', icon: '📊' },
  { id: 'doc-3', name: 'Extrait de Carrière', country: 'LU', flag: '🇱🇺', source: 'CNAP', status: 'missing', date: 'Not uploaded', type: 'Career Extract', icon: '📋' },
  { id: 'doc-4', name: 'AHV/AVS Extract', country: 'CH', flag: '🇨🇭', source: 'SVA', status: 'missing', date: 'Not uploaded', type: 'State Pension', icon: '🏛️' },
  { id: 'doc-5', name: 'Employment Certificate', country: 'CH', flag: '🇨🇭', source: 'Former employer', status: 'missing', date: 'Not uploaded', type: 'Employment', icon: '🏢' },
];

export const documentsAfter: PensionDocument[] = [
  { id: 'doc-1', name: 'Relevé de Carrière', country: 'FR', flag: '🇫🇷', source: 'CNAV', status: 'verified', date: '12 Mar 2026', type: 'Career Extract', icon: '📋' },
  { id: 'doc-2', name: 'Vorsorgeausweis', country: 'CH', flag: '🇨🇭', source: 'Pension Fund', status: 'verified', date: '10 Mar 2026', type: 'Pension Statement', icon: '📊' },
  { id: 'doc-3', name: 'Extrait de Carrière', country: 'LU', flag: '🇱🇺', source: 'CNAP', status: 'verified', date: '11 Mar 2026', type: 'Career Extract', icon: '📋' },
  { id: 'doc-4', name: 'AHV/AVS Extract', country: 'CH', flag: '🇨🇭', source: 'SVA', status: 'verified', date: '10 Mar 2026', type: 'State Pension', icon: '🏛️' },
  { id: 'doc-5', name: 'Employment Certificate', country: 'CH', flag: '🇨🇭', source: 'Former employer', status: 'pending', date: '14 Mar 2026', type: 'Employment', icon: '🏢' },
];

/** @deprecated Use documentsBefore / documentsAfter instead */
export const documents = documentsBefore;

export const riskAlerts: RiskAlert[] = [
  {
    id: 'alert-1',
    title: 'France Considering Raising Retirement Age to 65',
    description: 'A new legislative proposal introduced on 14 March 2026 would raise the minimum legal retirement age from 64 to 65 for those born after 1968. If adopted, your full-rate eligibility could shift by 12 months — potentially delaying your planned retirement from 2045 to 2046.',
    country: 'FR',
    flag: '🇫🇷',
    severity: 'high',
    impact: '−€2,520 estimated (1 yr delay)',
    timestamp: '2d ago',
    icon: '🔴',
    category: 'retirement_age',
    source: 'Assemblée Nationale · Projet de loi n° 2026-412',
    effectiveDate: 'Under debate — earliest Jan 2027',
  },
  {
    id: 'alert-2',
    title: 'Switzerland AVS Reform: Contribution Rate Increase',
    description: 'The Federal Council approved a 0.3% increase to AVS contribution rates starting January 2027 as part of AVS 22 stabilisation measures. While this doesn\'t affect your existing pension, it impacts your projected Swiss Pillar 1 accrual if you return to CH employment.',
    country: 'CH',
    flag: '🇨🇭',
    severity: 'medium',
    impact: 'Future accrual adjustment',
    timestamp: '5d ago',
    icon: '🟡',
    category: 'contribution',
    source: 'Federal Council press release · BSV/OFAS',
    effectiveDate: '1 Jan 2027',
  },
  {
    id: 'alert-3',
    title: 'Luxembourg CNAP Sustainability Review',
    description: 'The IGSS published its 2026 actuarial report recommending the government review the pension adjustment mechanism. The current 1.5x revalorisation coefficient may be reduced for high earners. Your Luxembourg pension (€980/mo) could see a 5–8% reduction in future indexation.',
    country: 'LU',
    flag: '🇱🇺',
    severity: 'medium',
    impact: '−€50 to −€78/mo long-term',
    timestamp: '1w ago',
    icon: '🟡',
    category: 'benefit',
    source: 'IGSS Bilan Technique 2026',
    effectiveDate: 'Recommendation phase — no date set',
  },
  {
    id: 'alert-4',
    title: 'France: CSG Rate Increase for Pension Income',
    description: 'Budget 2027 draft includes a proposal to raise CSG (social contribution) on pension income from 8.3% to 9.2% for taxpayers with RFR above €25,000. As a multi-country retiree in France, this would increase your annual social charges by approximately €400–€600.',
    country: 'FR',
    flag: '🇫🇷',
    severity: 'high',
    impact: '−€35 to −€50/mo net',
    timestamp: '3d ago',
    icon: '🔴',
    category: 'tax',
    source: 'Projet de Loi de Finances 2027 · Article 18',
    effectiveDate: 'Under debate — if passed, Jan 2027',
  },
  {
    id: 'alert-5',
    title: 'Switzerland: Cross-border Pension Taxation Treaty Update',
    description: 'France and Switzerland are renegotiating the double taxation convention on pension income. A draft amendment could change how your Swiss Pillar 2 lump sum is taxed if you retire in France — potentially moving from Swiss withholding tax (7.5%) to French progressive rates.',
    country: 'CH',
    flag: '🇨🇭',
    severity: 'high',
    impact: 'Up to +€12K tax on P2 capital',
    timestamp: '1w ago',
    icon: '🔴',
    category: 'tax',
    source: 'SIF / DGFiP bilateral consultation',
    effectiveDate: 'Negotiation phase — earliest 2028',
  },
  {
    id: 'alert-6',
    title: 'EU Portability Directive: Faster Pension Transfers',
    description: 'The European Commission published a proposal to simplify cross-border pension statement requests under the EU portability framework. If adopted, you may be able to request consolidated pension statements from FR, CH, and LU through a single digital portal.',
    country: 'EU',
    flag: '🇪🇺',
    severity: 'low',
    impact: 'Positive — easier access',
    timestamp: '2w ago',
    icon: '🟢',
    category: 'benefit',
    source: 'European Commission · COM(2026) 89',
    effectiveDate: 'Proposed — 2028 target',
  },
];

export const familyMembers: FamilyMember[] = [
  { id: 'fm-1', initials: 'AK', name: 'Anna Karlsson', relation: 'Spouse', accessLevel: 'full', gradientFrom: '#ec4899', gradientTo: '#f472b6' },
  { id: 'fm-2', initials: 'LK', name: 'Lea Karlsson', relation: 'Daughter', accessLevel: 'beneficiary', gradientFrom: '#8b5cf6', gradientTo: '#a78bfa' },
  { id: 'fm-3', initials: 'ON', name: 'Oscar Nilsson', relation: 'Brother', accessLevel: 'emergency', gradientFrom: '#06b6d4', gradientTo: '#22d3ee' },
  { id: 'fm-4', initials: 'EK', name: 'Erik Karlsson', relation: 'Father', accessLevel: 'readonly', gradientFrom: '#f97316', gradientTo: '#fb923c' },
];

export const capitalComponents: CapitalComponent[] = [
  { label: '🇫🇷 France · CNAV (P1)', country: 'FR', monthlyAnnuity: 1220, lumpSumOption: null, payoutType: 'annuity_only' },
  { label: '🇨🇭 Switzerland · AVS (P1)', country: 'CH', monthlyAnnuity: 320, lumpSumOption: null, payoutType: 'annuity_only' },
  { label: '🇱🇺 Luxembourg · CNAP (P1)', country: 'LU', monthlyAnnuity: 980, lumpSumOption: null, payoutType: 'annuity_only' },
];

export const servicePackages: ServicePackage[] = [
  {
    id: 'svc-1',
    name: 'Document Retrieval',
    category: 'document_retrieval',
    description: 'We contact pension bodies on your behalf and retrieve official career extracts, pension statements, and certificates from any country in your career.',
    features: [
      'Official document requests in local language',
      'Liaison with CNAV, AVS, CNAP & employer funds',
      'Translated summaries of key figures',
      'Digital copies uploaded to your vault',
    ],
    priceFrom: 99,
    currency: 'EUR',
    estimatedDays: 14,
    icon: '📄',
  },
  {
    id: 'svc-2',
    name: 'Gap Correction',
    category: 'gap_correction',
    description: 'We analyse your contribution gaps, determine which are correctable, and handle the buy-back or voluntary contribution process with the relevant pension body.',
    features: [
      'Gap impact analysis with monthly projections',
      'Eligibility check for voluntary buy-back',
      'Application filing with CNAP, CNAV, or AVS',
      'Cost-benefit report: buy-back cost vs. pension gain',
    ],
    priceFrom: 149,
    currency: 'EUR',
    estimatedDays: 21,
    icon: '🔧',
  },
  {
    id: 'svc-3',
    name: 'Pension Audit',
    category: 'pension_audit',
    description: 'A comprehensive review of your multi-country pension entitlements by a certified cross-border pension specialist. Covers all pillars in all countries.',
    features: [
      'Verification of Pillar 1 estimates against official data',
      'Pillar 2 fund location and valuation',
      'EU totalisation & coordination analysis',
      'Personalised report with actionable recommendations',
      'Follow-up call with the assigned expert',
    ],
    priceFrom: 299,
    currency: 'EUR',
    estimatedDays: 10,
    icon: '🔍',
    popular: true,
  },
  {
    id: 'svc-4',
    name: 'Tax Residency Analysis',
    category: 'tax_optimization',
    description: 'Detailed comparison of your net retirement income under different tax residency scenarios, including double taxation treaties and social charge implications.',
    features: [
      'Net income projection for up to 6 countries',
      'Double taxation treaty analysis for your pension mix',
      'Social charges & healthcare cost modelling',
      'Optimal timing & sequencing of pension claims',
      'Written report with tax advisor sign-off',
    ],
    priceFrom: 499,
    currency: 'EUR',
    estimatedDays: 15,
    icon: '💶',
  },
  {
    id: 'svc-5',
    name: 'Full Retirement Strategy',
    category: 'full_consultation',
    description: 'End-to-end retirement planning: from verifying every pension entitlement to optimising your claim strategy, tax residency, and capital vs. annuity decisions.',
    features: [
      'Everything in Pension Audit + Tax Analysis',
      'Pillar 2 capital vs. annuity modelling',
      'Claim sequencing strategy across all countries',
      'Family protection & survivor benefit review',
      'Ongoing support until all claims are filed',
    ],
    priceFrom: 899,
    currency: 'EUR',
    estimatedDays: 30,
    icon: '🎯',
  },
];

export const serviceRequests: ServiceRequest[] = [
  {
    id: 'req-1',
    packageId: 'svc-1',
    packageName: 'Document Retrieval',
    category: 'document_retrieval',
    status: 'completed',
    createdAt: '2026-02-10',
    updatedAt: '2026-02-24',
    price: 99,
    context: 'Retrieve French Relevé de Carrière from CNAV',
    notes: 'Document retrieved and uploaded to vault. 10.9 years confirmed.',
    assignedExpert: 'Marie Dupont',
  },
  {
    id: 'req-2',
    packageId: 'svc-3',
    packageName: 'Pension Audit',
    category: 'pension_audit',
    status: 'in_progress',
    createdAt: '2026-03-05',
    updatedAt: '2026-03-18',
    price: 349,
    context: 'Full audit of CH and LU pension entitlements',
    notes: 'Swiss AVS extract received. Awaiting UBS pension fund response. Luxembourg CNAP request filed.',
    assignedExpert: 'Thomas Weber',
  },
  {
    id: 'req-3',
    packageId: 'svc-2',
    packageName: 'Gap Correction',
    category: 'gap_correction',
    status: 'quote_sent',
    createdAt: '2026-03-19',
    updatedAt: '2026-03-20',
    price: 179,
    context: 'Chatbot escalation — Luxembourg 3-month gap correction',
    notes: 'Quote sent for CNAP voluntary buy-back filing. Estimated buy-back cost: €1,200. Pension gain: +€120/mo.',
  },
];
